### ISSUE TITLE
Calling Account Container from another container via Gateway

### ISSUE THREAD

**Issue by alihussain5286** [tanerdiler/spring-boot-microservice-eureka-zuul-docker#2]
Can you please tell me i have container which is not inside eureka or zuul proxy but it is build with Docker-compse so same network.

Example :

Service A not eureka client or part of Zuul

Service B(Authorization server) Eureka Client and Zuul routing is defined

Zuul -Proxy defined
     authorization:
      path: /authserver/**
      url: http://authorization:8082
 
Now from Service A i am calling rest call http://zuul-server:8401/authserver/oauth/token i am getting 404 can you please help me out

**Comment by devdcores** [comment]
@alihussain5286 make a network with type bridge in docker-compose and all containers to that network. 
example like this
networks:
  myNetwork:
    driver: bridge

There is a similar project like this, but it is more advanced and has monitoring setup and few other things, it is being developed by me, have a look at this. 
https://github.com/devdcores/BookStoreApp-Distributed-Application
