### ISSUE TITLE
Port binding

### ISSUE THREAD

**Issue by pathus90** [tanerdiler/spring-boot-microservice-eureka-zuul-docker#8]
In the docker file of the gateway module this is port 8761 is exposed et in the docker-compose.yml file the host is bound to port 8762. should we rather expose the port 8762 and not that of the discovery server 8761?

 gateway Dockerfie content

> FROM openjdk:11-jdk-slim
>MAINTAINER Taner Diler <taner.diler@gmail.com>
>ADD target/containerized-gateway.jar containerized-gateway.jar
>ENTRYPOINT ["java", "-jar", "/containerized-gateway.jar"]
>EXPOSE 8761 #we 

docker-compose.yml

gateway:
    image: tanerdiler/service-gateway
    container_name: service-gateway
    build:
      context: ./containerized-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    links:
      - discovery
      - logstash
      - zipkin

**Comment by tanerdiler** [comment]
Hi,

Is it still working with this conflict? Have you tried?

So, you are right and please send an Pull Request for it.

**Comment by pathus90** [comment]
Hi,
i have no permission to to send a Pull Request.
Br,

**Comment by tanerdiler** [comment]
Fixed

**Comment by pathus90** [comment]
I still have it
here is my logs

[spring-boot-microservice-eureka-zuul-docker] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/hotfix/gateway-port-8:hotfix/gateway-port-8 --set-upstream --force-with-lease=hotfix/gateway-port-8:
remote: Permission to tanerdiler/spring-boot-microservice-eureka-zuul-docker.git denied to pathus90.
fatal: unable to access 'https://github.com/tanerdiler/spring-boot-microservice-eureka-zuul-docker.git/': The requested URL returned error: 403

**Comment by tanerdiler** [comment]
Port changed on docker file.  You can send Pull Request after forking repository thus you are not contributor of this repository.

I'm closing this comment.

Thank you for your support.

**Comment by pathus90** [comment]
great, the bug is already fixed.
Br,
